
// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Wpilib.h"
#include "Loader.h"
#include "../Robotmap.h"
#include "../Commands/DoNothing.h"
Loader::Loader() : Subsystem("Loader") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	loaderController = RobotMap::loaderLoaderController;
	readySwitch = RobotMap::loaderReadySwitch;
	endSwitch = RobotMap::loaderEndSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Loader::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DoNothing());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Loader::Forward(){
	loaderController->Set(.3);
}
void Loader::Back(){
	loaderController->Set(-.3);
}
void Loader::Stop(){
	loaderController->Set(0);
}
bool Loader::GetReadySwitch(){
	readySwitch->Get();
}
bool Loader::GetEndSwitch(){
	endSwitch->Get();
}

// Put methods for controlling this subsystem
// here. Call these from Commands.
