// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainRightMotor = NULL;
SpeedController* RobotMap::driveTrainLeftMotor = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive21 = NULL;
SpeedController* RobotMap::shootingWheelShootingWheelController = NULL;
SpeedController* RobotMap::loaderLoaderController = NULL;
DigitalInput* RobotMap::loaderReadySwitch = NULL;
DigitalInput* RobotMap::loaderEndSwitch = NULL;
SpeedController* RobotMap::trackLifterTrackLifterController = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainRightMotor = new Jaguar(1, 2);
	lw->AddActuator("DriveTrain", "RightMotor", (Jaguar*) driveTrainRightMotor);
	
	driveTrainLeftMotor = new Jaguar(1, 1);
	lw->AddActuator("DriveTrain", "LeftMotor", (Jaguar*) driveTrainLeftMotor);
	
	driveTrainRobotDrive21 = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
	
	driveTrainRobotDrive21->SetSafetyEnabled(true);
        driveTrainRobotDrive21->SetExpiration(0.1);
        driveTrainRobotDrive21->SetSensitivity(0.5);
        driveTrainRobotDrive21->SetMaxOutput(1.0);
        driveTrainRobotDrive21->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);
        driveTrainRobotDrive21->SetInvertedMotor(RobotDrive::kRearRightMotor, true);        
	shootingWheelShootingWheelController = new Talon(1, 3);
	lw->AddActuator("ShootingWheel", "ShootingWheelController", (Talon*) shootingWheelShootingWheelController);
	
	loaderLoaderController = new Talon(1, 4);
	lw->AddActuator("Loader", "LoaderController", (Talon*) loaderLoaderController);
	
	loaderReadySwitch = new DigitalInput(1, 1);
	lw->AddSensor("Loader", "ReadySwitch", loaderReadySwitch);
	
	loaderEndSwitch = new DigitalInput(1, 2);
	lw->AddSensor("Loader", "EndSwitch", loaderEndSwitch);
	
	trackLifterTrackLifterController = new Talon(1, 5);
	lw->AddActuator("TrackLifter", "TrackLifterController", (Talon*) trackLifterTrackLifterController);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
